### PR TITLE
Android dev calendar list

### PR DESCRIPTION
**Pull request by oykuyilmaz1**
Can you review the code @darktheorys and I wrote for the calendar list @ertbulbul ? It is added on the home page of users.

### CODE REVIEW

**Review by ertbulbul — CHANGES_REQUESTED** [review]
Workspace items have border radius but others do nor, can you fix it?

**Comment by oykuyilmaz1** [comment]
Oh, I did not notice. It is a one minute change, I will fix it now.

**Comment by oykuyilmaz1** [comment]
Oh, I did not notice. It was a one minute change, I changed it. Can you check?

**Review by ertbulbul — APPROVED** [review]
It is ready to merge. Thanks for your effort.

**Pull request merged**
